#!/usr/bin/env ruby
#^syntax detection

#######################
# Community cookbooks #
#######################
site 'http://community.opscode.com/api/v1'

cookbook 'apache2', '1.1.12'
cookbook 'build-essential', '1.0.0'
cookbook 'runit', '0.13.0'
cookbook 'timezone', '0.0.1'
cookbook 'postfix', '1.2.0'
cookbook 'mysql', '1.3.0'
cookbook 'hostname', '0.0.2'
cookbook 'php', '1.0.2'
cookbook 'nginx', '0.101.6'
cookbook 'logrotate', '0.8.2'

##################################################
# Community cookbooks with pending pull requests #
##################################################
cookbook 'apt', :git => 'https://github.com/mrdavidlaing/apt'

####################
# Custom cookbooks #
####################

cookbook 'apache2-mpm-itk', 	:path => 'cookbooks-sources'
cookbook 'app_containers',  	:path => 'cookbooks-sources'
cookbook 'bash_for_hipsters', 	:path => 'cookbooks-sources'
cookbook 'htop', 				:path => 'cookbooks-sources'
cookbook 'multitail', 			:path => 'cookbooks-sources'
cookbook 'pressupbox', 			:path => 'cookbooks-sources'
cookbook 'unarchivers', 		:path => 'cookbooks-sources'
cookbook 'wp-cli', 				:path => 'cookbooks-sources'

###########
# Samples #
###########

#cookbook 'user',
#  :git => 'https://github.com/mrdavidlaing/chef-user',
#  :ref => 'add-group-docs'

# cookbook 'rvm',
#   :git => 'https://github.com/fnichol/chef-rvm'

# cookbook 'postgresql',
#   :git => 'https://github.com/findsyou/cookbooks',
#   :ref => 'postgresql-improvements'