maintainer        "David Laing"
maintainer_email  "david@davidlaing.com"
description       "Configure hosting container for webapps"
version           "0.17.1"

depends 		  "apache2"
depends 		  "apache2-mpm-itk"
depends 		  "bash_for_hipsters"
depends 		  "logrotate"
depends 		  "nginx"
depends 		  "mysql"
