maintainer       "PressUpBox"
maintainer_email "david@davidlaing.com"
license          "Apache v2"
description      "Combines a set of cookbooks to create a working PressUpBox"
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version          "0.0.1"
depends			 "apache2"
depends			 "apparmor"
depends			 "apt"
depends			 "hostname"
depends			 "htop"
depends			 "multitail"
depends			 "mysql"
depends			 "nginx"
depends			 "ossec"
depends			 "php"
depends			 "postfix"
depends			 "rsync"
depends			 "runit"
depends			 "timezone"
depends			 "unarchivers"
depends			 "xml"
depends			 "app_containers"